services:
  - type: web
    name: smart-price-tracker-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CRON_SECRET
        sync: false
